const app = require('../index')
const user = require('../model/schema')
const mongoose =require('../mongoose/DB') 
const controller = require('../routes/controller/controller')
const bookController = require('./controller/bookController')
const bookManager = require('./controller/bookManager')
app.post('/createUser',controller.createUser)
app.get('/sol1',controller.sol1)
app.post('/createPlayer',controller.createPlayer)
app.post('/person',controller.personOperate)
//Roll no 4 Book Name
app.post('/bookCreation',bookController.createBook1) 
app.post('/bookCreation/get',bookController.getBooks)
//Roll no 5 Author name Assignment/mongo-Day2
app.post('/createAuthor',bookManager.createAuthor)
app.post('/getAuthor',bookManager.getAuthor)
app.post('/getByYear',bookManager.yearData)
app.get('/searchBook',bookManager.searchEntire)
app.get('/getByINR',bookManager.getByINR) 
app.get('/stockChecker',bookManager.stockChecker)
app.get('/practice/:page',bookManager.practice)
module.exports=app        